### ISSUE TITLE
Training duration

### ISSUE THREAD

**Issue by slang-l** [tencent-ailab/season#4]
Hello, does model training require the use of eight GPUs? I use five pieces to reproduce CNN data. Does it take 60 hours for the Progress bar to display?

**Comment by FeiWang96** [comment]
You can find the average training time in our paper. To speed up, try deepspeed.

**Comment by slang-l** [comment]
Thank you. According to your open-source code and methods, can the CNN/DM dataset be trained in 5 hours?
